import React from 'react'

export const metadata = {
    title: "About",
    description: "Generated by create next app",
    keywords: "react, web development",
    author: "Your Name",
    // viewport: "width=device-width, initial-scale=1.0",
};

function page() {
  return (
    <div>
      about
    </div>
  )
}

export default page
