import Image from "next/image";
import Banner from "./components/Home/banner";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
  keywords: "next.js",
  author: "Your Name",
  // viewport: "width=device-width, initial-scale=1.0",
};

export default function Home() {
  return (
      <Banner/>
  );
}
